name: Pull request action approval
on:
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - '**pom.xml'
      - '!.github/**'
jobs:
  test-github-action:
    if: github.event.pull_request.user.login == 'SpeedLayerBot'
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: fileChanges
        uses: jitterbit/get-changed-files@v1
      - name: Check files for non pom.xml changes
        id: filesCheck
        run: |
          for changed_file in ${{ steps.fileChanges.outputs.all }}; do
            echo $changed_file
            if [[ $changed_file != *pom.xml ]]
            then
              NONRELCHANGES=true
              break
            fi
          done
          if [[ $NONRELCHANGES == false ]]
          then
            for changed_file in ${{ steps.fileChanges.outputs.removed }}; do
              echo $changed_file
              if [[ $changed_file == *pom.xml ]]
              then
                NONRELCHANGES=true
                break
              fi
            done
          fi
          if [[ $NONRELCHANGES == false ]]
          then
            for changed_file in ${{ steps.fileChanges.outputs.added }}; do
              echo $changed_file
              if [[ $changed_file == *pom.xml ]]
              then
                NONRELCHANGES=true
                break
              fi
            done
          fi
          echo '::set-output name=NONRELCHANGES::$NONRELCHANGES';
      - name: Approve Pull Request
        if: steps.filesCheck.outputs.nonRelChanges != 'true'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_TOKEN }}
          number: ${{ github.event.pull_request.number }}
      # - name: Merge Pull Request
      #   if: steps.filesCheck.outputs.nonRelChanges != 'true'
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.APPROVER_TOKEN }}
      #     number: ${{ github.event.pull_request.number }}
      #     method: squash