name: Pull request action approval
on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  test-github-action:
    if: github.event.pull_request.user.login == 'SpeedLayerBot'
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: fileChanges
        uses: jitterbit/get-changed-files@v1
      - name: Check files for non pom.xml changes
        id: filesCheck
        run: |
          for changed_file in ${{ steps.fileChanges.outputs.all }}; do
            if [[ $changed_file != *pom.xml ]]
            then
            fi
            echo '::set-output name=NONPOMCHANGES::false';
          done
      - name: Approve Pull Request
        if: steps.filesCheck.outputs.nonPomChanges != 'true'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_TOKEN }}
          number: ${{ github.event.pull_request.number }}