name: Pull request action approval
on:
  push:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  test-github-action:
    if: github.event.pull_request.user.login == "SpeedLayerBot"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "${{ github.event.pull_request }}"
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_TOKEN }}
          number: ${{ github.event.pull_request.number }}