name: Pull request action approval
on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  test-github-action:
    if: github.event.pull_request.user.login == 'SpeedLayerBot'
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        id: fileChanges
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.fileChanges.outputs.all }}; do
            echo $changed_file;
            if [[ $changed_file != *pom.xml ]]
            then
              run: echo '::set-output name=ONLY_POM_CHANGES::true';
            fi
          done
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_TOKEN }}
          number: ${{ github.event.pull_request.number }}